### ISSUE TITLE
Include postal code field

### ISSUE THREAD

**Issue by jpvillaisaza** [ondrap/geoip2#3]
The `GeoResult` type is missing some fields such as postal code, which seems like something simple to add.

(@ondrap We'd be happy to work on this if you're open to pull requests.)

**Comment by ondrap** [comment]
I hope it is simple to add, I just didn't quite knew what people would use it for, so I opted for a simple API.
Looking at the code... well, I think it would sure benefit from some rework - I didn't know `lens` at the time I was writing it and it seems to me it would simplify some things. Anyway, if you want to help and do a PR, you are very welcome.
